### ISSUE TITLE
About the number of parameters in figure 4

### ISSUE THREAD

**Issue by akqjq4985** [jaeho-lee/MetaSparseINR#1]
Hi! I would like to know why the number of parameters in figure 4 is 26561.

**Comment by jihoontack** [comment]
Hi, thank you for your interest in our paper :)

For the number, we report the # of parameters of the weight matrix (not the biases). Since we iteratively prune out the weights (not biases) by 20%, the calculation is as follows:
- total_weight = width * width * num_layers + width * dim_in + width * dim_out
- total_weight <- int (0.8 * total_weight) (repeat 9 times)
- Note that width = 256, num_layers = 3, dim_in = 2, dim_out =3

Best,
Jihoon
